name: Publish Docker images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-server-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}

      - name: Dokploy Deployment
        run: |
          curl -X 'POST' \
          'https://${{ secrets.DOKPLOY_URL }}/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.DOKPLOY_AUTH_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ secrets.DOKPLOY_APPLICATION_SERVER_ID }}"
              }
          }'

  build-and-push-bot-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-bot"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/bot/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Dokploy Deployment
        run: |
          curl -X 'POST' \
          'https://${{ secrets.DOKPLOY_URL }}/api/trpc/application.deploy' \
          -H 'accept: application/json' \
          -H 'Authorization: Bearer ${{ secrets.DOKPLOY_AUTH_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "json":{
                  "applicationId": "${{ secrets.DOKPLOY_APPLICATION_BOT_ID }}"
              }
          }'
